
SELECT * from salesrecords

1 .what is the total revenue generated by amazon across all regions and countries?

select SUM(Total_Revenue) AS TOTALREVENUE from salesrecords

TOTALREVENUE
137348768.31


2.which country has highest profit ?

select Total_Profit,Country from salesrecords
where Total_Profit= (select MAX(Total_Profit) from salesrecords)

1719922.04	Pakistan


3.which country has lowest profit ?
select Total_Profit,Country from salesrecords
where Total_Profit=(select MIN(Total_Profit) from salesrecords)

1258.02  Kuwait

4.what is the average unit price and unit cost of items sold in each regions?

select Region,ROUND(AVG(Unit_Price),2)AS average_unitprice,ROUND(AVG(Unit_Cost),2)AS average_unitcost from salesrecords
group by Region

5.which item type has highest sale volume(unit sold) overall?

select Item_Type, units_sold from salesrecords
where Units_Sold= (select MAX(Units_Sold) from salesrecords)

Baby Food  9925

6.How many orders were placed in each sales channel,and which channel has most orders?
select Sales_Channel,COUNT(Sales_Channel) AS Orders from salesrecords
group by Sales_Channel

Sales_Channel
Offline  50
Online   50

7.what is the distribution of order priority across all regions?
select Region, Order_Priority,count(*) AS priority_count from salesrecords
group by Region,Order_Priority
order by Region,Order_Priority 

8.what is the average shipping time( in days) for orders from each country?

select Country,avg(datediff(day,Ship_Date, Order_Date)) AS avg_shippingtime from salesrecords
group by Country

9.How does average total profit vary across different order priorities?

select Order_Priority,ROUND(avg(Total_Profit),2)AS avg_totalprofit from salesrecords
group by Order_Priority

10.Which month has highest  total revenue, which has lowest?

select month(Order_Date) AS max_revenue_month,Total_Revenue from salesrecords
where Total_Revenue= (select (MAX(Total_Revenue)) from salesrecords)

select month(Order_Date) AS min_revenue_month, Total_Revenue from salesrecords
where Total_Revenue= (select (MIN(Total_Revenue)) from salesrecords)

SELECT @@SERVERNAME

